//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGESysClient.GeneralServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeneralServiceReference.IGeneralService")]
    public interface IGeneralService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/Login", ReplyAction="http://tempuri.org/IGeneralService/LoginResponse")]
        bool Login(string idIn, string pwdIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/Login", ReplyAction="http://tempuri.org/IGeneralService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string idIn, string pwdIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/LoginAccountName", ReplyAction="http://tempuri.org/IGeneralService/LoginAccountNameResponse")]
        string LoginAccountName(string idIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/LoginAccountName", ReplyAction="http://tempuri.org/IGeneralService/LoginAccountNameResponse")]
        System.Threading.Tasks.Task<string> LoginAccountNameAsync(string idIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetStaffPosition", ReplyAction="http://tempuri.org/IGeneralService/GetStaffPositionResponse")]
        string GetStaffPosition(string idIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneralService/GetStaffPosition", ReplyAction="http://tempuri.org/IGeneralService/GetStaffPositionResponse")]
        System.Threading.Tasks.Task<string> GetStaffPositionAsync(string idIn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralServiceChannel : NGESysClient.GeneralServiceReference.IGeneralService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralServiceClient : System.ServiceModel.ClientBase<NGESysClient.GeneralServiceReference.IGeneralService>, NGESysClient.GeneralServiceReference.IGeneralService {
        
        public GeneralServiceClient() {
        }
        
        public GeneralServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string idIn, string pwdIn) {
            return base.Channel.Login(idIn, pwdIn);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string idIn, string pwdIn) {
            return base.Channel.LoginAsync(idIn, pwdIn);
        }
        
        public string LoginAccountName(string idIn) {
            return base.Channel.LoginAccountName(idIn);
        }
        
        public System.Threading.Tasks.Task<string> LoginAccountNameAsync(string idIn) {
            return base.Channel.LoginAccountNameAsync(idIn);
        }
        
        public string GetStaffPosition(string idIn) {
            return base.Channel.GetStaffPosition(idIn);
        }
        
        public System.Threading.Tasks.Task<string> GetStaffPositionAsync(string idIn) {
            return base.Channel.GetStaffPositionAsync(idIn);
        }
    }
}
