//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGEService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NGEsysDBEntities : DbContext
    {
        public NGEsysDBEntities()
            : base("name=NGEsysDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Layout> Layout { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
