//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGEService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Layout()
        {
            this.Article = new HashSet<Article>();
        }
    
        public string layoutID { get; set; }
        public System.DateTime lPubDate { get; set; }
        public string editor { get; set; }
        public string department { get; set; }
        public int lStatus { get; set; }
        public string lPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
